id: I566E95E1
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:18:56.720543
last_modified: 2023-02-10 00:18:56.720644
source_metadata:
  title: 'MSV 6,10: Mātṛkā'
  language: bo
bases:
  9CA6:
    base_file: 9CA6.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
